services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  TeaminmediasPluswerk\KeSearch\:
    resource: '../Classes/*'

  dashboard.widget.ke_search_indexer_status:
    class: 'TeaminmediasPluswerk\KeSearch\Widgets\StatusWidget'
    arguments:
      $view: '@dashboard.views.widget'
    tags:
      - name: dashboard.widget
        identifier: 'keSearchStatus'
        groupNames: 'ke_search'
        title: 'LLL:EXT:ke_search/Resources/Private/Language/locallang_dashboard.xml:widgets.keSearchStatus.title'
        description: 'LLL:EXT:ke_search/Resources/Private/Language/locallang_dashboard.xml:widgets.keSearchStatus.description'
        iconIdentifier: 'ext-kesearch-wizard-icon'
        height: 'small'
        width: 'small'

  dashboard.widget.ke_search_index_overview:
    class: 'TYPO3\CMS\Dashboard\Widgets\BarChartWidget'
    arguments:
      $dataProvider: '@TeaminmediasPluswerk\KeSearch\Widgets\Provider\IndexOverviewDataProvider'
      $view: '@dashboard.views.widget'
    tags:
      - name: dashboard.widget
        identifier: 'keSearchIndexOverview'
        groupNames: 'ke_search'
        title: 'LLL:EXT:ke_search/Resources/Private/Language/locallang_dashboard.xml:widgets.keSearchIndexOverview.title'
        description: 'LLL:EXT:ke_search/Resources/Private/Language/locallang_dashboard.xml:widgets.keSearchIndexOverview.description'
        iconIdentifier: 'ext-kesearch-wizard-icon'
        height: 'medium'
        width: 'medium'

  dashboard.widget.ke_search_trending_searchphrases:
    class: 'TYPO3\CMS\Dashboard\Widgets\ListWidget'
    arguments:
      $dataProvider: '@TeaminmediasPluswerk\KeSearch\Widgets\Provider\TrendingSearchphrasesDataProvider'
      $view: '@dashboard.views.widget'
    tags:
      - name: dashboard.widget
        identifier: 'keSearchTrendingSearchphrases'
        groupNames: 'ke_search'
        title: 'LLL:EXT:ke_search/Resources/Private/Language/locallang_dashboard.xml:widgets.keSearchTrendingSearchphrases.title'
        description: 'LLL:EXT:ke_search/Resources/Private/Language/locallang_dashboard.xml:widgets.keSearchTrendingSearchphrases.description'
        iconIdentifier: 'ext-kesearch-wizard-icon'
        height: 'medium'
        width: 'medium'
