services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  TeaminmediasPluswerk\KeSearch\:
    resource: '../Classes/*'

  dashboard.widget.teaminmedias_pluswerk.ke_search:
    class: 'TeaminmediasPluswerk\KeSearch\Widgets\StatusWidget'
    arguments:
      $view: '@dashboard.views.widget'
    tags:
      - name: dashboard.widget
        identifier: 'keSearchStatus'
        groupNames: 'ke_search'
        title: 'LLL:EXT:ke_search/Resources/Private/Language/locallang_dashboard.xml:widgets.keSearchStatus.title'
        description: 'LLL:EXT:ke_search/Resources/Private/Language/locallang_dashboard.xml:widgets.keSearchStatus.description'
        iconIdentifier: 'ext-kesearch-wizard-icon'
        height: 'small'
        width: 'small'